name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node.js
      uses: actions/setup-node@v1
    - run: npm install
    - run: npm run build
    - name: Create new release
      uses: fnkr/github-action-ghr@v1.3
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: zip
        GHR_PATH: .
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

